# Generated by Django 4.2.1 on 2023-06-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analityc', '0002_sell_delete_analityc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='date',
            new_name='created_at',
        ),
    ]
