# Generated by Django 4.2.1 on 2023-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organoleptica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organoleptica',
            name='particulas_extrañas',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='organoleptica',
            name='presenta_color',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='organoleptica',
            name='presenta_olor',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='organoleptica',
            name='presenta_sabor',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
    ]
